
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GCA(object):
    def setupUi(self, GCA):
        GCA.setObjectName("GCA")
        GCA.resize(1131, 613)
        self.gridLayout = QtWidgets.QGridLayout(GCA)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(GCA)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(120, 120, 781, 441))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(520, 50, 101, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(430, 50, 81, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.send_Button = QtWidgets.QPushButton(self.groupBox)
        self.send_Button.setGeometry(QtCore.QRect(540, 20, 81, 21))
        self.send_Button.setObjectName("send_Button")
        self.send_Text = QtWidgets.QLineEdit(self.groupBox)
        self.send_Text.setGeometry(QtCore.QRect(120, 20, 411, 22))
        self.send_Text.setObjectName("send_Text")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(120, 50, 101, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(10, 80, 611, 341))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(630, 20, 141, 191))
        self.groupBox_6.setObjectName("groupBox_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_6)
        self.textBrowser.setGeometry(QtCore.QRect(0, 20, 141, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setGeometry(QtCore.QRect(630, 220, 141, 201))
        self.groupBox_7.setObjectName("groupBox_7")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 20, 141, 181))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.clear_Button = QtWidgets.QPushButton(self.groupBox)
        self.clear_Button.setGeometry(QtCore.QRect(362, 50, 61, 21))
        self.clear_Button.setObjectName("clear_Button")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setGeometry(QtCore.QRect(910, 130, 191, 431))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, 0, 191, 461))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 101, 20))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(120, 0, 991, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 0, 171, 51))
        self.groupBox_8.setObjectName("groupBox_8")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButton.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.toolButton.setObjectName("toolButton")
        self.groupBox_17 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 50, 171, 41))
        self.groupBox_17.setObjectName("groupBox_17")
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_17)
        self.toolButton_3.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.toolButton_3.setObjectName("toolButton_3")
        self.groupBox_18 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_18.setGeometry(QtCore.QRect(820, 0, 171, 51))
        self.groupBox_18.setObjectName("groupBox_18")
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox_18)
        self.toolButton_4.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.toolButton_4.setObjectName("toolButton_4")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_18)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 50, 171, 51))
        self.groupBox_19.setObjectName("groupBox_19")
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox_19)
        self.toolButton_5.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.toolButton_5.setObjectName("toolButton_5")
        self.groupBox_20 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_20.setGeometry(QtCore.QRect(820, 50, 171, 51))
        self.groupBox_20.setObjectName("groupBox_20")
        self.toolButton_6 = QtWidgets.QToolButton(self.groupBox_20)
        self.toolButton_6.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolBox = QtWidgets.QToolBox(self.frame)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 111, 591))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 111, 405))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 111, 405))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_3 = QtWidgets.QLabel(self.page_6)
        self.label_3.setGeometry(QtCore.QRect(20, 370, 61, 31))
        self.label_3.setObjectName("label_3")
        self.toolBox.addItem(self.page_6, "")
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)

        self.retranslateUi(GCA)
        self.toolBox.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(GCA)
        GCA.setTabOrder(self.comboBox, self.comboBox_4)
        GCA.setTabOrder(self.comboBox_4, self.comboBox_5)
        GCA.setTabOrder(self.comboBox_5, self.send_Button)
        GCA.setTabOrder(self.send_Button, self.send_Text)
        GCA.setTabOrder(self.send_Text, self.checkBox)
        GCA.setTabOrder(self.checkBox, self.checkBox_2)
        GCA.setTabOrder(self.checkBox_2, self.scrollArea)

    def retranslateUi(self, GCA):
        _translate = QtCore.QCoreApplication.translate
        GCA.setWindowTitle(_translate("GCA", "RECEIVER "))
        self.groupBox.setTitle(_translate("GCA", "CONSOLE"))
        self.comboBox.setItemText(0, _translate("GCA", "SIGNAL OFF"))
        self.comboBox.setItemText(1, _translate("GCA", "SIGNAL ON"))
        self.comboBox_4.setItemText(0, _translate("GCA", "PLAIN TEXT "))
        self.comboBox_5.setItemText(0, _translate("GCA", "NEWLINE "))
        self.comboBox_5.setItemText(1, _translate("GCA", "NEXT LINE "))
        self.send_Button.setText(_translate("GCA", "SEND"))
        self.checkBox.setText(_translate("GCA", "AUTOSCROLL"))
        self.checkBox_2.setText(_translate("GCA", "TIMESTAMP"))
        self.label.setText(_translate("GCA", "NOT CONNECTED"))
        self.groupBox_6.setTitle(_translate("GCA", "PACKET INFO "))
        self.groupBox_7.setTitle(_translate("GCA", "COMMAND HISTORY"))
        self.clear_Button.setText(_translate("GCA", "clear"))
        self.label_2.setText(_translate("GCA", "RAW TELEMETRY"))
        self.groupBox_8.setTitle(_translate("GCA", "TIME "))
        self.toolButton.setText(_translate("GCA", "DISCONNECTED"))
        self.groupBox_17.setTitle(_translate("GCA", "BATTERY"))
        self.toolButton_3.setText(_translate("GCA", "DISCONNECTED"))
        self.groupBox_18.setTitle(_translate("GCA", "BATTERY"))
        self.toolButton_4.setText(_translate("GCA", "DISCONNECTED"))
        self.groupBox_19.setTitle(_translate("GCA", "TIME "))
        self.toolButton_5.setText(_translate("GCA", "DISCONNECTED"))
        self.groupBox_20.setTitle(_translate("GCA", "SIGNAL"))
        self.toolButton_6.setText(_translate("GCA", "DISCONNECTED"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("GCA", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("GCA", "Page 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("GCA", "Page"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("GCA", "Page"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("GCA", "Page"))
        self.label_3.setText(_translate("GCA", "WELCOME"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("GCA", "Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GCA = QtWidgets.QWidget()
    ui = Ui_GCA()
    ui.setupUi(GCA)
    GCA.show()
    sys.exit(app.exec_())
